name: macOS nightly wheel Build

on:
  push:
    tags:
    - v*.*.*
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 8 * * *"  # Runs at 8:00 UTC every day
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-nightly
  cancel-in-progress: true

jobs:
  build_wheels:
    name: "Build Wheels - Python ${{ matrix.python-version }}"
    runs-on: macos-15-large
    strategy:
      fail-fast: false # Allow other matrix jobs to continue if one fails
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Run build script
        shell: bash
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          pyenv global ${{ matrix.python-version }}
          source litert_env_${{ matrix.python-version }}/bin/activate

          # Add Homebrew Bazel to PATH if not already there
          export PATH="/opt/homebrew/bin:$PATH"

          export CI_BUILD_PYTHON=python${{ matrix.python-version }}
          export HERMETIC_PYTHON_VERSION=${{ matrix.python-version }}
          export USE_LOCAL_TF=false
          ./ci/build_pip_package_with_bazel.sh
       
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-py${{ matrix.python-version }}-${{ runner.os }}-${{ runner.arch }}
          path: ./dist/
