name: "windows_nightly_wheel"
on:
  #schedule:
    #- cron: "0 10 * * *"  # Run at 2am PST (10am UTC) every day to refresh the cache.

  workflow_dispatch:  # Manual trigger

jobs:
  build-and-nightly:
    name: "Build nightly Windows wheel - Python ${{ matrix.python-version }}"
    runs-on: Windows_x64  # Latest high spec runner ((96 cores and 384GB RAM)).
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    env:
      # Clear ANDROID_NDK_HOME as windows-latest has NDK where jobs don't have permission for
      # androidndk rulesto create symlinks.
      ANDROID_NDK_HOME:
      LITERT_MODELS: ""
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mount Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set USE_BAZEL_VERSION
        shell: bash
        run: |
          if [ -f .bazelversion ]; then
            echo "USE_BAZEL_VERSION=$(cat .bazelversion)" >> $GITHUB_ENV
          elif [ -f bazelversion ]; then
            echo "USE_BAZEL_VERSION=$(cat bazelversion)" >> $GITHUB_ENV
          fi

      - name: Set NIGHTLY_RELEASE_DATE
        run: |
          $date = Get-Date -Format "yyyyMMdd"
          echo "NIGHTLY_RELEASE_DATE=$date" >> $env:GITHUB_ENV

      - name: Configure tensorflow & python path
        run: |
          $env:PYTHON_BIN_PATH = (Get-Command python).Source
          $env:PYTHON_LIB_PATH = (python -c 'import site; print(site.getsitepackages()[0])')
          $env:TF_NEED_ROCM = 0
          $env:TF_NEED_CUDA = 0
          $env:TF_SET_ANDROID_WORKSPACE = 0
          $env:CC_OPT_FLAGS = '/arch:AVX'
          echo "HERMETIC_PYTHON_VERSION=${{ matrix.python-version }}" >> $env:GITHUB_ENV
          python configure.py

      - name: Build LiteRT wheel for Windows
        run: |
          .\ci\build_pip_package_with_bazel_windows.ps1

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: litert-windows-wheels-py${{ matrix.python-version }}
          path: dist/*.whl
